#!/bin/bash
# Verify bash version first
if (( BASH_VERSINFO[0] < 4 )); then
    echo "Error: Requires bash 4.0+" >&2
    exit 1
fi

# Detect distribution
DISTRO=""
if [[ -f /etc/os-release ]]; then
    source /etc/os-release
    DISTRO="$ID"
else
    DISTRO=$(uname -s)
fi

# Color definitions with underline support
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
NC=$(tput sgr0)
UNDERLINE=$(tput smul)
NOUNDERLINE=$(tput rmul)

# Modern command replacements
declare -A COMMAND_MAP=(
    # File Operations (1-20)
    ["go"]="ls"                       # List directory contents
    ["list"]="ls -l"                  # List files in detailed format
    ["create_file"]="touch"           # Create new empty files
    ["copy"]="cp"                     # Copy files/directories
    ["move"]="mv"                     # Move/rename files
    ["remove"]="rm"                   # Remove files/directories
    ["make_dir"]="mkdir"              # Create new directories
    ["link"]="ln"                     # Create file links
    ["compress"]="tar"                # Archive files (tar)
    ["compress_gz"]="gzip"            # Compress files (gzip)
    ["decompress_gz"]="gunzip"        # Decompress gzip files
    ["package_zip"]="zip"             # Create ZIP archives
    ["unpackage_zip"]="unzip"         # Extract ZIP archives
    ["sync_files"]="rsync"            # Efficient file synchronization
    ["change_group"]="chgrp"          # Change group ownership
    ["file_status"]="stat"            # Display file status
    ["file_type"]="file"              # Determine file type
    ["rename_files"]="rename"         # Batch rename files
    ["split_file"]="split"            # Split files into parts
    ["secure_delete"]="shred"         # Securely delete files

    # File Permissions (21-22)
    ["change_permissions"]="chmod"    # Modify file permissions
    ["change_owner"]="chown"          # Change file ownership

    # Process Management (23-32)
    ["processes"]="top"               # Display running processes
    ["show_processes"]="ps aux"       # Snapshot of current processes
    ["terminate"]="kill"              # Terminate processes by ID
    ["priority"]="nice"               # Set process priority
    ["interactive_top"]="htop"        # Interactive process viewer
    ["kill_all"]="killall"            # Kill processes by name
    ["process_kill"]="pkill"          # Kill processes by pattern
    ["process_grep"]="pgrep"          # Find processes by pattern
    ["background_jobs"]="jobs"        # List background jobs
    ["resume_background"]="bg"        # Resume job in background

    # Networking (33-47)
    ["download"]="wget"               # Download files from web
    ["check_connection"]="ping"       # Test network connectivity
    ["remote_login"]="ssh"            # Secure shell remote access
    ["secure_copy"]="scp"             # Securely copy between hosts
    ["network_stats"]="ss"            # Socket statistics (replaces netstat)
    ["trace_route"]="traceroute"      # Trace network path
    ["dns_lookup"]="dig"              # DNS lookup utility
    ["network_scan"]="nmap"           # Network exploration tool
    ["dns_query"]="host"              # DNS lookup utility
    ["domain_info"]="whois"           # WHOIS domain lookup
    ["packet_capture"]="tcpdump"      # Capture network packets
    ["netcat"]="nc"                   # Read/write network connections
    ["ssh_keygen"]="ssh-keygen"       # Generate SSH keys
    ["copy_ssh_key"]="ssh-copy-id"    # Install SSH key on remote
    ["network_diagnostic"]="mtr"      # Network diagnostic tool

    # System Info (48-60)
    ["disk_space"]="df -h"            # Show disk space usage
    ["disk_usage"]="du -sh"           # Estimate file space usage
    ["show_host"]="hostname"          # Display system hostname
    ["config_network"]="ip"           # Modern network config (replaces ifconfig)
    ["show_routing"]="ip route"       # Modern routing table (replaces route)
    ["system_uptime"]="uptime"        # Show system uptime
    ["memory_usage"]="free -h"        # Display memory usage
    ["system_info"]="uname -a"        # Display system information
    ["block_devices"]="lsblk"         # List block devices
    ["cpu_info"]="lscpu"              # Show CPU architecture
    ["hardware_info"]="lshw"          # List hardware components
    ["kernel_messages"]="dmesg"       # Print kernel messages
    ["system_logs"]="journalctl"      # Query systemd journal

    # Text Processing (61-72)
    ["search"]="grep"                 # Search text patterns
    ["show_end"]="tail"               # Display file tail
    ["show_start"]="head"             # Display file head
    ["pager"]="less"                  # View file contents
    ["sort_lines"]="sort"             # Sort text lines
    ["unique_lines"]="uniq"           # Filter duplicate lines
    ["cut_sections"]="cut"            # Cut sections from lines
    ["pattern_scan"]="awk"            # Pattern scanning language
    ["stream_edit"]="sed"             # Stream text editor
    ["count_words"]="wc"              # Count lines/words/characters
    ["compare_files"]="diff"          # Compare files line-by-line
    ["byte_compare"]="cmp"            # Compare files byte-by-byte

    # Package Management (73-75)
    ["install_pkg"]="_detect_installer"
    ["update_pkg"]="_detect_updater"
    ["upgrade_system"]="_detect_upgrader"

    # System Services (76-80)
    ["manage_services"]="systemctl"   # Control system services
    ["start_service"]="systemctl"     # Universal systemctl command
    ["service_status"]="systemctl status"    # Check service status
    ["enable_service"]="systemctl enable"    # Enable service at boot
    ["disable_service"]="systemctl disable"  # Disable service

    # User Management (81-88)
    ["change_password"]="passwd"      # Change user password
    ["add_user"]="useradd"            # Create new user account
    ["add_group"]="groupadd"          # Create new user group
    ["modify_user"]="usermod"         # Modify user account
    ["delete_user"]="userdel"         # Delete user account
    ["delete_group"]="groupdel"       # Delete group
    ["user_groups"]="groups"          # Show user's groups
    ["user_info"]="id"                # Display user/group info

    # File Content (89-90)
    ["read_file"]="cat"               # Display file contents
    ["edit"]="nano"                   # Simple text editor

    # Search Utilities (91-92)
    ["find"]="find"                   # Search for files
    ["locate_file"]="locate"          # Find files quickly

    # Misc Utilities (93-100)
    ["manual"]="man"                  # Display manual pages
    ["http_client"]="curl"            # Transfer data from URLs
    ["command_history"]="history"     # Show command history
    ["print_text"]="echo"             # Display message/text
    ["schedule_tasks"]="crontab -e"   # Edit scheduled tasks
    ["open_files"]="lsof"             # List open files
    ["firewall"]="iptables"           # Configure firewall rules
    ["switch_user"]="su"              # Switch user identity
)

# Distribution-specific package management
case "$DISTRO" in
    debian|ubuntu)
        COMMAND_MAP["install_pkg"]="apt-get install"
        COMMAND_MAP["update_pkg"]="apt-get update"
        COMMAND_MAP["upgrade_system"]="apt-get upgrade"
        ;;
    opensuse*)
        COMMAND_MAP["install_pkg"]="zypper install"
        COMMAND_MAP["update_pkg"]="zypper refresh"
        COMMAND_MAP["upgrade_system"]="zypper update"
        ;;
    manjaro|arch)
        COMMAND_MAP["install_pkg"]="pacman -S"
        COMMAND_MAP["update_pkg"]="pacman -Sy"
        COMMAND_MAP["upgrade_system"]="pacman -Syu"
        ;;
    *)
        echo "Unsupported distribution: $DISTRO" >&2
        exit 1
        ;;
esac

# Command explanations
declare -A EXPLANATIONS=(
    # File Operations (1-20)
    ["go"]="List directory contents in simple format"
    ["list"]="List files with detailed information (permissions, size, etc.)"
    ["create_file"]="Create new empty file(s)"
    ["copy"]="Copy files or directories"
    ["move"]="Move or rename files/directories"
    ["remove"]="Remove files or directories"
    ["make_dir"]="Create new directory(ies)"
    ["link"]="Create hard or symbolic links"
    ["compress"]="Create tar archive of files/directories"
    ["compress_gz"]="Compress files using gzip"
    ["decompress_gz"]="Decompress gzipped files"
    ["package_zip"]="Create ZIP archive"
    ["unpackage_zip"]="Extract ZIP archive contents"
    ["sync_files"]="Efficient file synchronization between locations"
    ["change_group"]="Change group ownership of files"
    ["file_status"]="Display detailed file metadata and status"
    ["file_type"]="Determine file type and format"
    ["rename_files"]="Batch rename files using patterns"
    ["split_file"]="Split large files into smaller parts"
    ["secure_delete"]="Securely overwrite and delete files"

    # File Permissions (21-22)
    ["change_permissions"]="Modify file/directory permissions"
    ["change_owner"]="Change file/directory ownership"

    # Process Management (23-32)
    ["processes"]="Display dynamic real-time view of running processes"
    ["show_processes"]="Show snapshot of current processes"
    ["terminate"]="Send signal to terminate a process"
    ["priority"]="Run program with modified scheduling priority"
    ["interactive_top"]="Interactive process viewer with hotkeys"
    ["kill_all"]="Terminate processes by name"
    ["process_kill"]="Terminate processes by pattern matching"
    ["process_grep"]="Find processes by name pattern"
    ["background_jobs"]="List current background jobs"
    ["resume_background"]="Resume suspended job in background"

    # Networking (33-47)
    ["download"]="Download files from the internet"
    ["check_connection"]="Test network connectivity to a host"
    ["remote_login"]="Secure shell client for remote login"
    ["secure_copy"]="Securely copy files between hosts"
    ["network_stats"]="Display socket statistics (modern replacement for netstat)"
    ["trace_route"]="Print network path to remote host"
    ["dns_lookup"]="DNS lookup and troubleshooting tool"
    ["network_scan"]="Network exploration and security auditing"
    ["dns_query"]="DNS lookup utility with simple output"
    ["domain_info"]="Lookup domain registration information"
    ["packet_capture"]="Capture and analyze network traffic"
    ["netcat"]="Read/write data across network connections"
    ["ssh_keygen"]="Generate SSH authentication keys"
    ["copy_ssh_key"]="Install SSH public key on remote server"
    ["network_diagnostic"]="Combined traceroute and ping tool"

    # System Info (48-60)
    ["disk_space"]="Show disk space usage in human-readable format"
    ["disk_usage"]="Estimate file space usage"
    ["show_host"]="Display system's host name"
    ["config_network"]="Modern network interface configuration"
    ["show_routing"]="Display IP routing table"
    ["system_uptime"]="Show system uptime and load averages"
    ["memory_usage"]="Display memory usage statistics"
    ["system_info"]="Print system and kernel information"
    ["block_devices"]="List information about block devices"
    ["cpu_info"]="Display CPU architecture information"
    ["hardware_info"]="Detailed hardware configuration report"
    ["kernel_messages"]="Display kernel ring buffer messages"
    ["system_logs"]="Query systemd journal logs"

    # Text Processing (61-72)
    ["search"]="Search text patterns using regular expressions"
    ["show_end"]="Display last part of files"
    ["show_start"]="Display first part of files"
    ["pager"]="View file contents with navigation"
    ["sort_lines"]="Sort lines of text files"
    ["unique_lines"]="Filter adjacent duplicate lines"
    ["cut_sections"]="Remove sections from each line of files"
    ["pattern_scan"]="Powerful text processing language"
    ["stream_edit"]="Stream editor for text transformation"
    ["count_words"]="Count lines, words, and characters"
    ["compare_files"]="Compare files line by line"
    ["byte_compare"]="Compare files at byte level"

    # Package Management (73-75)
    ["install_pkg"]="Install software packages"
    ["update_pkg"]="Refresh package repository metadata"
    ["upgrade_system"]="Upgrade all installed packages"

    # System Services (76-80)
    ["manage_services"]="Control systemd services and units"
    ["start_service"]="Start system services via systemctl"
    ["service_status"]="Check service status and logs"
    ["enable_service"]="Enable service to start at boot"
    ["disable_service"]="Disable service from auto-starting"

    # User Management (81-88)
    ["change_password"]="Change user password"
    ["add_user"]="Create new user account"
    ["add_group"]="Create new user group"
    ["modify_user"]="Modify existing user account"
    ["delete_user"]="Delete user account"
    ["delete_group"]="Delete user group"
    ["user_groups"]="Show group membership for user"
    ["user_info"]="Display user identity information"

    # File Content (89-90)
    ["read_file"]="Display entire file content"
    ["edit"]="Simple terminal text editor"

    # Search Utilities (91-92)
    ["find"]="Search for files in directory hierarchy"
    ["locate_file"]="Find files using prebuilt database"

    # Misc Utilities (93-100)
    ["manual"]="Display command reference manuals"
    ["http_client"]="Transfer data from/to servers"
    ["command_history"]="Display command history list"
    ["print_text"]="Display message or variable content"
    ["schedule_tasks"]="Edit scheduled cron jobs"
    ["open_files"]="List open files and processes"
    ["firewall"]="Configure network firewall rules"
    ["switch_user"]="Change user identity during session"
)

# Argument translations
declare -A ARG_TRANSLATIONS=(
    # Common flags (101-110)
    ["-v"]="Verbose output mode"
    ["-f"]="Force operation/override warnings"
    ["-r"]="Recursive directory operation"
    ["-y"]="Automatic yes to prompts"
    ["-R"]="Recursive directory traversal"
    ["-i"]="Case-insensitive search"
    ["-h"]="Human-readable format"
    ["-a"]="Show all/hidden items"
    ["-l"]="Long listing format"
    ["-s"]="Silent/quiet mode"

    # Package management (111-113)
    ["apt-get install"]="Install packages (Debian/Ubuntu)"
    ["zypper install"]="Install packages (openSUSE)"
    ["pacman -S"]="Install packages (Arch/Manjaro)"

    # Network commands (114-119)
    ["ip addr"]="Show IP addresses and interfaces"
    ["ip link"]="Manage network interfaces"
    ["ss -tuln"]="Show listening TCP/UDP ports"
    ["nmap -sV"]="Service version detection scan"
    ["tcpdump -i"]="Capture traffic on specific interface"
    ["curl -O"]="Download file with original name"

    # System commands (120-125)
    ["systemctl status"]="Check service status and logs"
    ["journalctl -xe"]="Detailed system log view"
    ["lsblk -o NAME,SIZE"]="List block devices with size"
    ["free -m"]="Show memory in megabytes"
    ["df -i"]="Show inode usage statistics"
    ["du -x"]="Exclude mounted filesystems"

    # Dangerous commands (126-130)
    ["rm -rf"]="Force recursive deletion (DANGEROUS)"
    ["chmod 777"]="Set full permissions for all (INSECURE)"
    ["kill -9"]="Force process termination (SIGKILL)"
    ["dd if=/dev"]="Raw disk operations (CAUTION)"
    ["mkfs.*"]="Format filesystem (DATA LOSS RISK)"

    # Text processing (131-135)
    ["grep -E"]="Extended regular expressions"
    ["awk '{print $1}'"]="Print first column"
    ["sed -i"]="In-place file modification"
    ["sort -n"]="Numerical sorting"
    ["uniq -c"]="Count unique occurrences"

    # User management (136-140)
    ["useradd -m"]="Create user with home directory"
    ["passwd -l"]="Lock user account"
    ["usermod -aG"]="Add user to supplementary groups"
    ["chown -R"]="Recursive ownership change"
    ["chmod +x"]="Make file executable"
)

# Helper functions
get_explanation() {
    local cmd="$1"
    echo "${EXPLANATIONS[$cmd]:-No explanation available for this command}"
}

get_argument_explanation() {
    local arg="$1"
    echo "${ARG_TRANSLATIONS[$arg]:-No explanation available for this argument}"
}

# Final validation check
if ! declare -p COMMAND_MAP 2>/dev/null | grep -q 'declare \-A'; then
    echo "CRITICAL ERROR: Failed to initialize COMMAND_MAP" >&2
    exit 1
fi

# Exported Commands
export A2DISCONF=a2disconf
export A2DISMOD=a2dismod
export A2DISSITE=a2dissite
export A2ENCONF=a2enconf
export A2ENMOD=a2enmod
export A2ENSITE=a2ensite
export A2QUERY=a2query
export AA_ENABLED=aa_enabled
export AA_EXEC=aa_exec
export AA_FEATURES_ABI=aa_features_abi
export AA_REMOVE_UNKNOWN=aa_remove_unknown
export AA_STATUS=aa_status
export AA_TEARDOWN=aa_teardown
export AB=ab
export ACCESSDB=accessdb
export ACONNECT=aconnect
export ACORN=acorn
export ADD_APT_REPOSITORY=add_apt_repository
export ADDGNUPGHOME=addgnupghome
export ADDGROUP=addgroup
export ADDPART=addpart
export ADDR2LINE=addr2line
export ADD_SHELL=add_shell
export ADDUSER=adduser
export AGETTY=agetty
export AIRSCAN_DISCOVER=airscan_discover
export ALIAS=alias
export ALSABAT=alsabat
export ALSABAT_TEST=alsabat_test
export ALSACTL=alsactl
export ALSA_INFO=alsa_info
export ALSALOOP=alsaloop
export ALSAMIXER=alsamixer
export ALSATPLG=alsatplg
export ALSAUCM=alsaucm
export AMIDI=amidi
export AMIXER=amixer
export AMUFORMAT_SH=amuFormat_sh
export ANACRON=anacron
export ANALOG=analog
export APACHE2=apache2
export APACHE2CTL=apache2ctl
export APACHECTL=apachectl
export APG=apg
export APGBFM=apgbfm
export APLAY=aplay
export APLAYMIDI=aplaymidi
export APPARMOR_PARSER=apparmor_parser
export APPARMOR_STATUS=apparmor_status
export APPLYGNUPGDEFAULTS=applygnupgdefaults
export APPRES=appres
export APPSTREAMCLI=appstreamcli
export APROPOS=apropos
export APT=apt
export APT_ADD_REPOSITORY=apt_add_repository
export APT_CACHE=apt_cache
export APT_CDROM=apt_cdrom
export APT_CONFIG=apt_config
export APT_EXTRACTTEMPLATES=apt_extracttemplates
export APT_FTPARCHIVE=apt_ftparchive
export APT_GET=apt_get
export APT_KEY=apt_key
export APT_LISTCHANGES=apt_listchanges
export APT_MARK=apt_mark
export APT_SORTPKGS=apt_sortpkgs
export AR=ar
export ARBORIST=arborist
export ARCH=arch
export ARECORD=arecord
export ARECORDMIDI=arecordmidi
export ARPD=arpd
export ARPTABLES=arptables
export ARPTABLES_NFT=arptables_nft
export ARPTABLES_NFT_RESTORE=arptables_nft_restore
export ARPTABLES_NFT_SAVE=arptables_nft_save
export ARPTABLES_RESTORE=arptables_restore
export ARPTABLES_SAVE=arptables_save
export AS=as
export ASEQDUMP=aseqdump
export ASEQNET=aseqnet
export ASPELL=aspell
export ASPELL_AUTOBUILDHASH=aspell_autobuildhash
export ASPELL_IMPORT=aspell_import
export ATOBM=atobm
export AVAHI_DAEMON=avahi_daemon
export AWK=awk
export AXFER=axfer
export B2SUM=b2sum
export BABELJS=babeljs
export BABELJS_7=babeljs_7
export BABELJS_7_EXTERNAL_HELPERS=babeljs_7_external_helpers
export BABELJS_7_NODE=babeljs_7_node
export BABELJS_7_PARSER=babeljs_7_parser
export BABELJS_EXTERNAL_HELPERS=babeljs_external_helpers
export BABELJS_NODE=babeljs_node
export BABELJS_PARSER=babeljs_parser
export BADBLOCKS=badblocks
export BAOBAB=baobab
export BASE32=base32
export BASE64=base64
export BASENAME=basename
export BASENC=basenc
export BASH=bash
export BASHBUG=bashbug
export BC=bc
export BDFTOPCF=bdftopcf
export BDFTRUNCATE=bdftruncate
export BF_COMPACT=bf_compact
export BF_COMPACT_BDB=bf_compact_bdb
export BF_COPY=bf_copy
export BF_COPY_BDB=bf_copy_bdb
export BF_TAR=bf_tar
export BF_TAR_BDB=bf_tar_bdb
export BG=bg
export BIND=bind
export BIOSDECODE=biosdecode
export BITMAP=bitmap
export BLKDEACTIVATE=blkdeactivate
export BLKDISCARD=blkdiscard
export BLKID=blkid
export BLKZONE=blkzone
export BLOCKDEV=blockdev
export BLUEMOON=bluemoon
export BLUETOOTHCTL=bluetoothctl
export BLUETOOTHD=bluetoothd
export BLUETOOTH_SENDTO=bluetooth_sendto
export BMTOA=bmtoa
export BOCHS=bochs
export BOCHS_BIN=bochs_bin
export BOGOFILTER=bogofilter
export BOGOFILTER_BDB=bogofilter_bdb
export BOGOLEXER=bogolexer
export BOGOLEXER_BDB=bogolexer_bdb
export BOGOTUNE=bogotune
export BOGOTUNE_BDB=bogotune_bdb
export BOGOUPGRADE=bogoupgrade
export BOGOUPGRADE_BDB=bogoupgrade_bdb
export BOGOUTIL=bogoutil
export BOGOUTIL_BDB=bogoutil_bdb
export BOLTCTL=boltctl
export BREAK=break
export BRIDGE=bridge
export BROADWAYD=broadwayd
export BROWSERSLIST=browserslist
export BTATTACH=btattach
export BTMGMT=btmgmt
export BTMON=btmon
export BUILDHASH=buildhash
export BUILTIN=builtin
export BUNZIP2=bunzip2
export BUSCTL=busctl
export BUSYBOX=busybox
export BWRAP=bwrap
export BXHUB=bxhub
export BXIMAGE=bximage
export BZCAT=bzcat
export BZCMP=bzcmp
export BZDIFF=bzdiff
export BZEGREP=bzegrep
export BZEXE=bzexe
export BZFGREP=bzfgrep
export BZGREP=bzgrep
export BZIP2=bzip2
export BZIP2RECOVER=bzip2recover
export BZLESS=bzless
export BZMORE=bzmore
export C_=c_
export C89=c89
export C89_GCC=c89_gcc
export C99=c99
export C99_GCC=c99_gcc
export CACHE_CHECK=cache_check
export CACHE_DUMP=cache_dump
export CACHE_METADATA_SIZE=cache_metadata_size
export CACHE_REPAIR=cache_repair
export CACHE_RESTORE=cache_restore
export CACHE_WRITEBACK=cache_writeback
export CALLER=caller
export CANCEL=cancel
export CAPSH=capsh
export CAPTOINFO=captoinfo
export CASE=case
export CAT=cat
export CATMAN=catman
export CC=cc
export CD=cd
export CD_CREATE_PROFILE=cd_create_profile
export CD_FIX_PROFILE=cd_fix_profile
export CD_ICCDUMP=cd_iccdump
export CD_IT8=cd_it8
export CDRDAO=cdrdao
export CERTTOOL=certtool
export CFDISK=cfdisk
export C_FILT=c_filt
export CGDISK=cgdisk
export CHACL=chacl
export CHAGE=chage
export CHARDET=chardet
export CHARDETECT=chardetect
export CHAT=chat
export CHATTR=chattr
export CHCON=chcon
export CHCPU=chcpu
export CHECK_FORENSIC=check_forensic
export CHECKGID=checkgid
export CHEESE=cheese
export CHFN=chfn
export CHGPASSWD=chgpasswd
export CHGRP=chgrp
export CHKFONT=chkfont
export CHMEM=chmem
export CHMOD=chmod
export CHOOM=choom
export CHOWN=chown
export CHPASSWD=chpasswd
export CHROOT=chroot
export CHRT=chrt
export CHSH=chsh
export CHVT=chvt
export CIPTOOL=ciptool
export CKBCOMP=ckbcomp
export CKSUM=cksum
export CLEAR=clear
export CLEAR_CONSOLE=clear_console
export CLION=clion
export CMP=cmp
export CODE=code
export CODEPAGE=codepage
export COL=col
export COLCRT=colcrt
export COLORMGR=colormgr
export COLRM=colrm
export COLUMN=column
export COMM=comm
export COMMAND=command
export COMPGEN=compgen
export COMPLETE=complete
export COMPOPT=compopt
export COMPOSE=compose
export CONTINUE=continue
export COPROC=coproc
export CORELIST=corelist
export CP=cp
export CPAN=cpan
export CPAN5_36_X86_64_LINUX_GNU=cpan5_36_x86_64_linux_gnu
export CPGR=cpgr
export CPIO=cpio
export CPP=cpp
export CPP_12=cpp_12
export CPPW=cppw
export CRACKLIB_CHECK=cracklib_check
export CRACKLIB_FORMAT=cracklib_format
export CRACKLIB_PACKER=cracklib_packer
export CRACKLIB_UNPACKER=cracklib_unpacker
export CREATE_CRACKLIB_DICT=create_cracklib_dict
export C_REHASH=c_rehash
export CRON=cron
export CRONTAB=crontab
export CSPLIT=csplit
export CTRLALTDEL=ctrlaltdel
export CTSTAT=ctstat
export CUPSACCEPT=cupsaccept
export CUPS_BROWSED=cups_browsed
export CUPSCTL=cupsctl
export CUPSD=cupsd
export CUPSDISABLE=cupsdisable
export CUPSENABLE=cupsenable
export CUPSFILTER=cupsfilter
export CUPSREJECT=cupsreject
export CUPSTESTPPD=cupstestppd
export CUT=cut
export CVT=cvt
export CVTSUDOERS=cvtsudoers
export DANETOOL=danetool
export DASH=dash
export DATE=date
export DBUS_CLEANUP_SOCKETS=dbus_cleanup_sockets
export DBUS_DAEMON=dbus_daemon
export DBUS_MONITOR=dbus_monitor
export DBUS_RUN_SESSION=dbus_run_session
export DBUS_SEND=dbus_send
export DBUS_UPDATE_ACTIVATION_ENVIRONMENT=dbus_update_activation_environment
export DBUS_UUIDGEN=dbus_uuidgen
export DBXTOOL=dbxtool
export DCB=dcb
export DCONF=dconf
export DD=dd
export DEALLOCVT=deallocvt
export DEBCONF=debconf
export DEBCONF_APT_PROGRESS=debconf_apt_progress
export DEBCONF_COMMUNICATE=debconf_communicate
export DEBCONF_COPYDB=debconf_copydb
export DEBCONF_ESCAPE=debconf_escape
export DEBCONF_SET_SELECTIONS=debconf_set_selections
export DEBCONF_SHOW=debconf_show
export DEBIANBTS=debianbts
export DEB_SYSTEMD_HELPER=deb_systemd_helper
export DEB_SYSTEMD_INVOKE=deb_systemd_invoke
export DEBUGFS=debugfs
export DECLARE=declare
export DEFMT_C=defmt_c
export DEFMT_SH=defmt_sh
export DELGROUP=delgroup
export DELPART=delpart
export DELUSER=deluser
export DELV=delv
export DEPMOD=depmod
export DEQUOTE=dequote
export DESKTOP_FILE_EDIT=desktop_file_edit
export DESKTOP_FILE_INSTALL=desktop_file_install
export DESKTOP_FILE_VALIDATE=desktop_file_validate
export DEVLINK=devlink
export DF=df
export DH_BASH_COMPLETION=dh_bash_completion
export DHCLIENT=dhclient
export DHCLIENT_SCRIPT=dhclient_script
export DH_INSTALLXMLCATALOGS=dh_installxmlcatalogs
export DH_PERL_OPENSSL=dh_perl_openssl
export DIFF=diff
export DIFF3=diff3
export DIG=dig
export DIR=dir
export DIRCOLORS=dircolors
export DIRMNGR=dirmngr
export DIRMNGR_CLIENT=dirmngr_client
export DIRNAME=dirname
export DIRS=dirs
export DISCOVER=discover
export DISCOVER_CONFIG=discover_config
export DISCOVER_MODPROBE=discover_modprobe
export DISCOVER_PKGINSTALL=discover_pkginstall
export DISOWN=disown
export DKMS=dkms
export DMESG=dmesg
export DMEVENTD=dmeventd
export DMIDECODE=dmidecode
export DMSETUP=dmsetup
export DMSTATS=dmstats
export DNSDOMAINNAME=dnsdomainname
export DNSMASQ=dnsmasq
export DNSTAP_READ=dnstap_read
export DO=do
export DOMAINNAME=domainname
export DONE=done
export DOSFSCK=dosfsck
export DOSFSLABEL=dosfslabel
export DOTLOCKFILE=dotlockfile
export DPKG=dpkg
export DPKG_ARCHITECTURE=dpkg_architecture
export DPKG_BUILDFLAGS=dpkg_buildflags
export DPKG_BUILDPACKAGE=dpkg_buildpackage
export DPKG_CHECKBUILDDEPS=dpkg_checkbuilddeps
export DPKG_DEB=dpkg_deb
export DPKG_DISTADDFILE=dpkg_distaddfile
export DPKG_DIVERT=dpkg_divert
export DPKG_FSYS_USRUNMESS=dpkg_fsys_usrunmess
export DPKG_GENBUILDINFO=dpkg_genbuildinfo
export DPKG_GENCHANGES=dpkg_genchanges
export DPKG_GENCONTROL=dpkg_gencontrol
export DPKG_GENSYMBOLS=dpkg_gensymbols
export DPKG_MAINTSCRIPT_HELPER=dpkg_maintscript_helper
export DPKG_MERGECHANGELOGS=dpkg_mergechangelogs
export DPKG_NAME=dpkg_name
export DPKG_PARSECHANGELOG=dpkg_parsechangelog
export DPKG_PRECONFIGURE=dpkg_preconfigure
export DPKG_QUERY=dpkg_query
export DPKG_REALPATH=dpkg_realpath
export DPKG_RECONFIGURE=dpkg_reconfigure
export DPKG_SCANPACKAGES=dpkg_scanpackages
export DPKG_SCANSOURCES=dpkg_scansources
export DPKG_SHLIBDEPS=dpkg_shlibdeps
export DPKG_SOURCE=dpkg_source
export DPKG_SPLIT=dpkg_split
export DPKG_STATOVERRIDE=dpkg_statoverride
export DPKG_TRIGGER=dpkg_trigger
export DPKG_VENDOR=dpkg_vendor
export DRIVERLESS=driverless
export DRIVERLESS_FAX=driverless_fax
export DU=du
export DUMPE2FS=dumpe2fs
export DUMP_EXFAT=dump_exfat
export DUMPKEYS=dumpkeys
export DVIPDF=dvipdf
export DWP=dwp
export E2FREEFRAG=e2freefrag
export E2FSCK=e2fsck
export E2IMAGE=e2image
export E2LABEL=e2label
export E2MMPSTATUS=e2mmpstatus
export E2SCRUB=e2scrub
export E2SCRUB_ALL=e2scrub_all
export E2UNDO=e2undo
export E4CRYPT=e4crypt
export E4DEFRAG=e4defrag
export EBTABLES=ebtables
export EBTABLES_NFT=ebtables_nft
export EBTABLES_NFT_RESTORE=ebtables_nft_restore
export EBTABLES_NFT_SAVE=ebtables_nft_save
export EBTABLES_RESTORE=ebtables_restore
export EBTABLES_SAVE=ebtables_save
export EBTABLES_TRANSLATE=ebtables_translate
export ECHO=echo
export EDIT=edit
export EDITOR=editor
export EDITRES=editres
export EFIBOOTDUMP=efibootdump
export EFIBOOTMGR=efibootmgr
export EGREP=egrep
export EJECT=eject
export ELFEDIT=elfedit
export ELIF=elif
export ELSE=else
export ENABLE=enable
export ENC2XS=enc2xs
export ENCGUESS=encguess
export ENCHANT_2=enchant_2
export ENCHANT_LSMOD_2=enchant_lsmod_2
export ENV=env
export ENVSUBST=envsubst
export EOG=eog
export EPS2EPS=eps2eps
export EQN=eqn
export ERA_CHECK=era_check
export ERA_DUMP=era_dump
export ERA_INVALIDATE=era_invalidate
export ERA_RESTORE=era_restore
export ESAC=esac
export ESCODEGEN=escodegen
export ESGENERATE=esgenerate
export ESLINT=eslint
export ESPARSE=esparse
export ESVALIDATE=esvalidate
export EVAL=eval
export EVINCE=evince
export EVINCE_PREVIEWER=evince_previewer
export EVINCE_THUMBNAILER=evince_thumbnailer
export EVOLUTION=evolution
export EX=ex
export EXEC=exec
export EXFAT2IMG=exfat2img
export EXFATLABEL=exfatlabel
export EXIT=exit
export EXPAND=expand
export EXPIRY=expiry
export EXPORT=export
export EXPR=expr
export FACTOR=factor
export FAILLOCK=faillock
export FAILLOG=faillog
export FAKED_SYSV=faked_sysv
export FAKED_TCP=faked_tcp
export FAKEROOT=fakeroot
export FAKEROOT_SYSV=fakeroot_sysv
export FAKEROOT_TCP=fakeroot_tcp
export FALLOCATE=fallocate
export FALSE=false
export FATLABEL=fatlabel
export FC=fc
export FC_CACHE=fc_cache
export FC_CAT=fc_cat
export FC_CONFLIST=fc_conflist
export FCGISTARTER=fcgistarter
export FC_LIST=fc_list
export FC_MATCH=fc_match
export FC_PATTERN=fc_pattern
export FC_QUERY=fc_query
export FC_SCAN=fc_scan
export FC_VALIDATE=fc_validate
export FDISK=fdisk
export FG=fg
export FGCONSOLE=fgconsole
export FGREP=fgrep
export FI=fi
export FIGLET=figlet
export FIGLET_FIGLET=figlet_figlet
export FIGLIST=figlist
export FILE=file
export FILE2BRL=file2brl
export FILEFRAG=filefrag
export FILE_ROLLER=file_roller
export FINCORE=fincore
export FIND=find
export FINDAFFIX=findaffix
export FINDFS=findfs
export FINDMNT=findmnt
export FIREFOX=firefox
export FIREFOX_ESR=firefox_esr
export FIVE_OR_MORE=five_or_more
export FIXPARTS=fixparts
export FLOCK=flock
export FMT=fmt
export FOLD=fold
export FONTTOSFNT=fonttosfnt
export FOOMATIC_RIP=foomatic_rip
export FOR=for
export FOUR_IN_A_ROW=four_in_a_row
export FREE=free
export FSADM=fsadm
export FSCK=fsck
export FSCK_CRAMFS=fsck_cramfs
export FSCK_EXFAT=fsck_exfat
export FSCK_EXT2=fsck_ext2
export FSCK_EXT3=fsck_ext3
export FSCK_EXT4=fsck_ext4
export FSCK_FAT=fsck_fat
export FSCK_MINIX=fsck_minix
export FSCK_MSDOS=fsck_msdos
export FSCK_VFAT=fsck_vfat
export FSFREEZE=fsfreeze
export FSTAB_DECODE=fstab_decode
export FSTRIM=fstrim
export FUNCTION=function
export FUNZIP=funzip
export FUSER=fuser
export FUSERMOUNT=fusermount
export FUSERMOUNT3=fusermount3
export FWUPDMGR=fwupdmgr
export FWUPDTOOL=fwupdtool
export G_=g_
export G__12=g__12
export GAMMA4SCANIMAGE=gamma4scanimage
export GAPPLICATION=gapplication
export GATTTOOL=gatttool
export GCALCCMD=gcalccmd
export GCC=gcc
export GCC_12=gcc_12
export GCC_AR=gcc_ar
export GCC_AR_12=gcc_ar_12
export GCC_NM=gcc_nm
export GCC_NM_12=gcc_nm_12
export GCC_RANLIB=gcc_ranlib
export GCC_RANLIB_12=gcc_ranlib_12
export GCM_IMPORT=gcm_import
export GCM_INSPECT=gcm_inspect
export GCM_PICKER=gcm_picker
export GCM_VIEWER=gcm_viewer
export GCORE=gcore
export GCOV=gcov
export GCOV_12=gcov_12
export GCOV_DUMP=gcov_dump
export GCOV_DUMP_12=gcov_dump_12
export GCOV_TOOL=gcov_tool
export GCOV_TOOL_12=gcov_tool_12
export GCR_VIEWER=gcr_viewer
export GDB=gdb
export GDB_ADD_INDEX=gdb_add_index
export GDBTUI=gdbtui
export GDBUS=gdbus
export GDIALOG=gdialog
export GDISK=gdisk
export GDK_PIXBUF_CSOURCE=gdk_pixbuf_csource
export GDK_PIXBUF_PIXDATA=gdk_pixbuf_pixdata
export GDK_PIXBUF_THUMBNAILER=gdk_pixbuf_thumbnailer
export GDM3=gdm3
export GDMFLEXISERVER=gdmflexiserver
export GDM_SCREENSHOT=gdm_screenshot
export GENCAT=gencat
export GENL=genl
export GEQN=geqn
export GET=GET
export GETCAP=getcap
export GETCONF=getconf
export GETENT=getent
export GETFACL=getfacl
export GETKEYCODES=getkeycodes
export GETOPT=getopt
export GETOPTS=getopts
export GETPCAPS=getpcaps
export GETTEXT=gettext
export GETTEXT_SH=gettext_sh
export GETTY=getty
export GHOSTSCRIPT=ghostscript
export GIO=gio
export GIO_QUERYMODULES=gio_querymodules
export GIT=git
export GIT_RECEIVE_PACK=git_receive_pack
export GIT_SHELL=git_shell
export GIT_UPLOAD_ARCHIVE=git_upload_archive
export GIT_UPLOAD_PACK=git_upload_pack
export GJS=gjs
export GJS_CONSOLE=gjs_console
export GKBD_KEYBOARD_DISPLAY=gkbd_keyboard_display
export GLIB_COMPILE_SCHEMAS=glib_compile_schemas
export GMAKE=gmake
export GNOME_2048=gnome_2048
export GNOME_BROWSER_CONNECTOR=gnome_browser_connector
export GNOME_BROWSER_CONNECTOR_HOST=gnome_browser_connector_host
export GNOME_CALCULATOR=gnome_calculator
export GNOME_CALENDAR=gnome_calendar
export GNOME_CHARACTERS=gnome_characters
export GNOME_CHESS=gnome_chess
export GNOME_CLOCKS=gnome_clocks
export GNOME_CONTACTS=gnome_contacts
export GNOME_CONTROL_CENTER=gnome_control_center
export GNOME_DISK_IMAGE_MOUNTER=gnome_disk_image_mounter
export GNOME_DISKS=gnome_disks
export GNOME_EXTENSIONS=gnome_extensions
export GNOME_EXTENSIONS_APP=gnome_extensions_app
export GNOME_FONT_VIEWER=gnome_font_viewer
export GNOME_HELP=gnome_help
export GNOME_KEYRING=gnome_keyring
export GNOME_KEYRING_3=gnome_keyring_3
export GNOME_KEYRING_DAEMON=gnome_keyring_daemon
export GNOME_KLOTSKI=gnome_klotski
export GNOME_LOGS=gnome_logs
export GNOME_MAHJONGG=gnome_mahjongg
export GNOME_MAPS=gnome_maps
export GNOME_MENUS_BLACKLIST=gnome_menus_blacklist
export GNOME_MINES=gnome_mines
export GNOME_MUSIC=gnome_music
export GNOME_NIBBLES=gnome_nibbles
export GNOME_ROBOTS=gnome_robots
export GNOME_SESSION=gnome_session
export GNOME_SESSION_CLASSIC=gnome_session_classic
export GNOME_SESSION_INHIBIT=gnome_session_inhibit
export GNOME_SESSION_QUIT=gnome_session_quit
export GNOME_SHELL=gnome_shell
export GNOME_SHELL_EXTENSION_PREFS=gnome_shell_extension_prefs
export GNOME_SHELL_EXTENSION_TOOL=gnome_shell_extension_tool
export GNOME_SHELL_PERF_TOOL=gnome_shell_perf_tool
export GNOME_SOFTWARE=gnome_software
export GNOME_SOUND_RECORDER=gnome_sound_recorder
export GNOME_SUDOKU=gnome_sudoku
export GNOME_SYSTEM_MONITOR=gnome_system_monitor
export GNOME_TAQUIN=gnome_taquin
export GNOME_TERMINAL=gnome_terminal
export GNOME_TERMINAL_WRAPPER=gnome_terminal_wrapper
export GNOME_TETRAVEX=gnome_tetravex
export GNOME_TEXT_EDITOR=gnome_text_editor
export GNOME_THUMBNAIL_FONT=gnome_thumbnail_font
export GNOME_TWEAKS=gnome_tweaks
export GNOME_WEATHER=gnome_weather
export GNOME_WWW_BROWSER=gnome_www_browser
export GNUTLS_CLI=gnutls_cli
export GNUTLS_CLI_DEBUG=gnutls_cli_debug
export GNUTLS_SERV=gnutls_serv
export GOLD=gold
export GP_ARCHIVE=gp_archive
export GPASSWD=gpasswd
export GP_COLLECT_APP=gp_collect_app
export GP_DISPLAY_HTML=gp_display_html
export GP_DISPLAY_SRC=gp_display_src
export GP_DISPLAY_TEXT=gp_display_text
export GPG=gpg
export GPG_AGENT=gpg_agent
export GPGCOMPOSE=gpgcompose
export GPGCONF=gpgconf
export GPG_CONNECT_AGENT=gpg_connect_agent
export GPGPARSEMAIL=gpgparsemail
export GPGSM=gpgsm
export GPGSPLIT=gpgsplit
export GPGTAR=gpgtar
export GPGV=gpgv
export GPG_WKS_SERVER=gpg_wks_server
export GPG_ZIP=gpg_zip
export GPIC=gpic
export GPROF=gprof
export GPROFNG=gprofng
export GRDCTL=grdctl
export GREP=grep
export GRESOURCE=gresource
export GROFF=groff
export GROG=grog
export GROPS=grops
export GROTTY=grotty
export GROUPADD=groupadd
export GROUPDEL=groupdel
export GROUPMEMS=groupmems
export GROUPMOD=groupmod
export GROUPS=groups
export GRPCK=grpck
export GRPCONV=grpconv
export GRPUNCONV=grpunconv
export GRUB_EDITENV=grub_editenv
export GRUB_FILE=grub_file
export GRUB_FSTEST=grub_fstest
export GRUB_GLUE_EFI=grub_glue_efi
export GRUB_INSTALL=grub_install
export GRUB_KBDCOMP=grub_kbdcomp
export GRUB_MACBLESS=grub_macbless
export GRUB_MENULST2CFG=grub_menulst2cfg
export GRUB_MKCONFIG=grub_mkconfig
export GRUB_MKDEVICEMAP=grub_mkdevicemap
export GRUB_MKFONT=grub_mkfont
export GRUB_MKIMAGE=grub_mkimage
export GRUB_MKLAYOUT=grub_mklayout
export GRUB_MKNETDIR=grub_mknetdir
export GRUB_MKPASSWD_PBKDF2=grub_mkpasswd_pbkdf2
export GRUB_MKRELPATH=grub_mkrelpath
export GRUB_MKRESCUE=grub_mkrescue
export GRUB_MKSTANDALONE=grub_mkstandalone
export GRUB_MOUNT=grub_mount
export GRUB_PROBE=grub_probe
export GRUB_REBOOT=grub_reboot
export GRUB_RENDER_LABEL=grub_render_label
export GRUB_SCRIPT_CHECK=grub_script_check
export GRUB_SET_DEFAULT=grub_set_default
export GRUB_SYSLINUX2CFG=grub_syslinux2cfg
export GS=gs
export GSBJ=gsbj
export GSDJ=gsdj
export GSDJ500=gsdj500
export GSETTINGS=gsettings
export GSF=gsf
export GSF_OFFICE_THUMBNAILER=gsf_office_thumbnailer
export GSF_VBA_DUMP=gsf_vba_dump
export GSLJ=gslj
export GSLP=gslp
export GSND=gsnd
export GSTREAMER_CODEC_INSTALL=gstreamer_codec_install
export GTBL=gtbl
export GTED=gted
export GTF=gtf
export GTK4_BROADWAYD=gtk4_broadwayd
export GTK4_BUILDER_TOOL=gtk4_builder_tool
export GTK4_ENCODE_SYMBOLIC_SVG=gtk4_encode_symbolic_svg
export GTK4_LAUNCH=gtk4_launch
export GTK4_QUERY_SETTINGS=gtk4_query_settings
export GTK4_UPDATE_ICON_CACHE=gtk4_update_icon_cache
export GTK_BUILDER_TOOL=gtk_builder_tool
export GTK_ENCODE_SYMBOLIC_SVG=gtk_encode_symbolic_svg
export GTK_LAUNCH=gtk_launch
export GTK_QUERY_SETTINGS=gtk_query_settings
export GTK_UPDATE_ICON_CACHE=gtk_update_icon_cache
export GUNZIP=gunzip
export GYP=gyp
export GZEXE=gzexe
export GZIP=gzip
export H2PH=h2ph
export H2XS=h2xs
export HALT=halt
export HANDLEBARS=handlebars
export HARDLINK=hardlink
export HASH=hash
export HCIATTACH=hciattach
export HCICONFIG=hciconfig
export HCITOOL=hcitool
export HD=hd
export HEAD=head
export HEAD=HEAD
export HELP=help
export HELPZTAGS=helpztags
export HEX2HCD=hex2hcd
export HEXDUMP=hexdump
export HISTORY=history
export HITORI=hitori
export HOICHESS=hoichess
export HOIXIANGQI=hoixiangqi
export HOST=host
export HOSTID=hostid
export HOSTNAME=hostname
export HOSTNAMECTL=hostnamectl
export HTCACHECLEAN=htcacheclean
export HTDBM=htdbm
export HTDIGEST=htdigest
export HTPASSWD=htpasswd
export HTTXT2DBM=httxt2dbm
export HWCLOCK=hwclock
export I386=i386
export IAGNO=iagno
export IBUS=ibus
export IBUS_DAEMON=ibus_daemon
export IBUS_SETUP=ibus_setup
export ICEAUTH=iceauth
export ICO=ico
export ICOMBINE=icombine
export ICONV=iconv
export ICONVCONFIG=iconvconfig
export ID=id
export IECSET=iecset
export IF=if
export IFDOWN=ifdown
export IFQUERY=ifquery
export IFUP=ifup
export IIO_SENSOR_PROXY=iio_sensor_proxy
export IJOIN=ijoin
export IM_CONFIG=im_config
export IM_LAUNCH=im_launch
export IN=in
export INETUTILS_TELNET=inetutils_telnet
export INFOCMP=infocmp
export INFOTOCAP=infotocap
export INIT=init
export INSMOD=insmod
export INSTALL=install
export INSTALLKERNEL=installkernel
export INSTALL_SGMLCATALOG=install_sgmlcatalog
export INSTMODSH=instmodsh
export INTEL_VIRTUAL_OUTPUT=intel_virtual_output
export INVOKE_RC_D=invoke_rc_d
export IONICE=ionice
export IP=ip
export IP6TABLES=ip6tables
export IP6TABLES_APPLY=ip6tables_apply
export IP6TABLES_LEGACY=ip6tables_legacy
export IP6TABLES_LEGACY_RESTORE=ip6tables_legacy_restore
export IP6TABLES_LEGACY_SAVE=ip6tables_legacy_save
export IP6TABLES_NFT=ip6tables_nft
export IP6TABLES_NFT_RESTORE=ip6tables_nft_restore
export IP6TABLES_NFT_SAVE=ip6tables_nft_save
export IP6TABLES_RESTORE=ip6tables_restore
export IP6TABLES_RESTORE_TRANSLATE=ip6tables_restore_translate
export IP6TABLES_SAVE=ip6tables_save
export IP6TABLES_TRANSLATE=ip6tables_translate
export IPCMK=ipcmk
export IPCRM=ipcrm
export IPCS=ipcs
export IPOD_READ_SYSINFO_EXTENDED=ipod_read_sysinfo_extended
export IPOD_TIME_SYNC=ipod_time_sync
export IPPEVEPCL=ippevepcl
export IPPEVEPRINTER=ippeveprinter
export IPPEVEPS=ippeveps
export IPPFIND=ippfind
export IPPTOOL=ipptool
export IPP_USB=ipp_usb
export IPTABLES=iptables
export IPTABLES_APPLY=iptables_apply
export IPTABLES_LEGACY=iptables_legacy
export IPTABLES_LEGACY_RESTORE=iptables_legacy_restore
export IPTABLES_LEGACY_SAVE=iptables_legacy_save
export IPTABLES_NFT=iptables_nft
export IPTABLES_NFT_RESTORE=iptables_nft_restore
export IPTABLES_NFT_SAVE=iptables_nft_save
export IPTABLES_RESTORE=iptables_restore
export IPTABLES_RESTORE_TRANSLATE=iptables_restore_translate
export IPTABLES_SAVE=iptables_save
export IPTABLES_TRANSLATE=iptables_translate
export IPTABLES_XML=iptables_xml
export ISCHROOT=ischroot
export ISDV4_SERIAL_DEBUGGER=isdv4_serial_debugger
export ISDV4_SERIAL_INPUTATTACH=isdv4_serial_inputattach
export ISOSIZE=isosize
export ISPELL=ispell
export ISPELL_AUTOBUILDHASH=ispell_autobuildhash
export ISPELL_WRAPPER=ispell_wrapper
export ISTANBUL=istanbul
export IUCODE_TOOL=iucode_tool
export IUCODE_TOOL=iucode_tool
export IW=iw
export JOBS=jobs
export JOIN=join
export JOURNALCTL=journalctl
export JQ=jq
export JS=js
export JSESC=jsesc
export JSON5=json5
export JSON_PP=json_pp
export JS_YAML=js_yaml
export JXRDECAPP=JxrDecApp
export JXRENCAPP=JxrEncApp
export KACTIVITIES_CLI=kactivities_cli
export KBDINFO=kbdinfo
export KBD_MODE=kbd_mode
export KBDRATE=kbdrate
export KBOOKMARKMERGER=kbookmarkmerger
export KBUILDSYCOCA5=kbuildsycoca5
export KBXUTIL=kbxutil
export KCOOKIEJAR5=kcookiejar5
export KDED5=kded5
export KDE_GEO_URI_HANDLER=kde_geo_uri_handler
export KEDITBOOKMARKS=keditbookmarks
export KERNEL_INSTALL=kernel_install
export KGLOBALACCEL5=kglobalaccel5
export KICONFINDER5=kiconfinder5
export KILL=kill
export KILLALL=killall
export KILLALL5=killall5
export KMOD=kmod
export KONSOLE=konsole
export KONSOLEPROFILE=konsoleprofile
export KPACKAGELAUNCHERQML=kpackagelauncherqml
export KPACKAGETOOL5=kpackagetool5
export KQUITAPP5=kquitapp5
export KREADCONFIG5=kreadconfig5
export KTELNETSERVICE5=ktelnetservice5
export KTRASH5=ktrash5
export KVM=kvm
export KWALLETD5=kwalletd5
export KWALLET_QUERY=kwallet_query
export KWRITECONFIG5=kwriteconfig5
export L2PING=l2ping
export L2TEST=l2test
export LAPTOP_DETECT=laptop_detect
export LAST=last
export LASTB=lastb
export LASTLOG=lastlog
export LCF=lcf
export LD=ld
export LDATTACH=ldattach
export LD_BFD=ld_bfd
export LDCONFIG=ldconfig
export LDD=ldd
export LD_GOLD=ld_gold
export LD_SO=ld_so
export LEARNTERMINALTN=learnTerminalTN
export LESS=less
export LESSECHO=lessecho
export LESSFILE=lessfile
export LESSKEY=lesskey
export LESSPIPE=lesspipe
export LET=let
export LEXGROG=lexgrog
export LFT=lft
export LFT_DB=lft_db
export LIBNETCFG=libnetcfg
export LIBREOFFICE=libreoffice
export LIBVIRTD=libvirtd
export LIGHTSOFF=lightsoff
export LINK=link
export LINUX32=linux32
export LINUX64=linux64
export LINUX_BOOT_PROBER=linux_boot_prober
export LINUX_CHECK_REMOVAL=linux_check_removal
export LINUX_UPDATE_SYMLINKS=linux_update_symlinks
export LINUX_VERSION=linux_version
export LISTRES=listres
export LN=ln
export LNSTAT=lnstat
export LOADKEYS=loadkeys
export LOADUNIMAP=loadunimap
export LOCAL=local
export LOCALC=localc
export LOCALE=locale
export LOCALECTL=localectl
export LOCALEDEF=localedef
export LOCALE_GEN=locale_gen
export LODRAW=lodraw
export LOFFICE=loffice
export LOFROMTEMPLATE=lofromtemplate
export LOGGER=logger
export LOGIN=login
export LOGINCTL=loginctl
export LOGNAME=logname
export LOGOUT=logout
export LOGRESOLVE=logresolve
export LOGROTATE=logrotate
export LOGSAVE=logsave
export LOIMPRESS=loimpress
export LOMATH=lomath
export LOOK=look
export LOSETUP=losetup
export LOWEB=loweb
export LOWNTFS_3G=lowntfs_3g
export LOWRITER=lowriter
export LP=lp
export LPADMIN=lpadmin
export LPINFO=lpinfo
export LPMOVE=lpmove
export LPOPTIONS=lpoptions
export LP_SOLVE=lp_solve
export LPSTAT=lpstat
export LS=ls
export LSATTR=lsattr
export LSBLK=lsblk
export LSB_RELEASE=lsb_release
export LSCPU=lscpu
export LSFD=lsfd
export LSINITRAMFS=lsinitramfs
export LSIPC=lsipc
export LSIRQ=lsirq
export LSLOCKS=lslocks
export LSLOGINS=lslogins
export LSMDEV=lsmdev
export LSMEM=lsmem
export LSMOD=lsmod
export LSNS=lsns
export LSOF=lsof
export LSPCI=lspci
export LSPGPOT=lspgpot
export LSUSB=lsusb
export LTO_DUMP=lto_dump
export LTO_DUMP_12=lto_dump_12
export LUIT=luit
export LVCHANGE=lvchange
export LVCONVERT=lvconvert
export LVCREATE=lvcreate
export LVDISPLAY=lvdisplay
export LVEXTEND=lvextend
export LVM=lvm
export LVMCONFIG=lvmconfig
export LVMDISKSCAN=lvmdiskscan
export LVMDUMP=lvmdump
export LVMPOLLD=lvmpolld
export LVMSADC=lvmsadc
export LVMSAR=lvmsar
export LVREDUCE=lvreduce
export LVREMOVE=lvremove
export LVRENAME=lvrename
export LVRESIZE=lvresize
export LVS=lvs
export LVSCAN=lvscan
export LWP_DOWNLOAD=lwp_download
export LWP_DUMP=lwp_dump
export LWP_MIRROR=lwp_mirror
export LWP_REQUEST=lwp_request
export LYNX=lynx
export LZ=lz
export LZCAT=lzcat
export LZCMP=lzcmp
export LZDIFF=lzdiff
export LZEGREP=lzegrep
export LZFGREP=lzfgrep
export LZGREP=lzgrep
export LZLESS=lzless
export LZMA=lzma
export LZMAINFO=lzmainfo
export LZMORE=lzmore
export MACHINECTL=machinectl
export MAKE=make
export MAKE_FIRST_EXISTING_TARGET=make_first_existing_target
export MAKE_SSL_CERT=make_ssl_cert
export MAKO_RENDER=mako_render
export MALCONTENT_CLIENT=malcontent_client
export MALCONTENT_CONTROL=malcontent_control
export MAN=man
export MANDB=mandb
export MANPATH=manpath
export MAN_RECODE=man_recode
export MAPFILE=mapfile
export MAPSCRN=mapscrn
export MATTRIB=mattrib
export MAWK=mawk
export MBADBLOCKS=mbadblocks
export MBIMCLI=mbimcli
export MBIM_NETWORK=mbim_network
export MCAT=mcat
export MCD=mcd
export MCHECK=mcheck
export MCLASSERASE=mclasserase
export MCOMP=mcomp
export MCOOKIE=mcookie
export MCOPY=mcopy
export MD5SUM=md5sum
export MD5SUM_TEXTUTILS=md5sum_textutils
export MDEL=mdel
export MDELTREE=mdeltree
export MDEVCTL=mdevctl
export MDIG=mdig
export MDIR=mdir
export MDU=mdu
export MEMUSAGE=memusage
export MEMUSAGESTAT=memusagestat
export MESA_OVERLAY_CONTROL_PY=mesa_overlay_control_py
export MESG=mesg
export MFORMAT=mformat
export MICRO=micro
export MIGRATE_PUBRING_FROM_CLASSIC_GPG=migrate_pubring_from_classic_gpg
export MIMEOPEN=mimeopen
export MIMETYPE=mimetype
export MINFO=minfo
export MKDIR=mkdir
export MKDOSFS=mkdosfs
export MKE2FS=mke2fs
export MKFIFO=mkfifo
export MKFONTDIR=mkfontdir
export MKFONTSCALE=mkfontscale
export MKFS=mkfs
export MKFS_BFS=mkfs_bfs
export MKFS_CRAMFS=mkfs_cramfs
export MKFS_EXFAT=mkfs_exfat
export MKFS_EXT2=mkfs_ext2
export MKFS_EXT3=mkfs_ext3
export MKFS_EXT4=mkfs_ext4
export MKFS_FAT=mkfs_fat
export MKFS_MINIX=mkfs_minix
export MKFS_MSDOS=mkfs_msdos
export MKFS_NTFS=mkfs_ntfs
export MKFS_VFAT=mkfs_vfat
export MKHOMEDIR_HELPER=mkhomedir_helper
export MKINITRAMFS=mkinitramfs
export MKLOST_FOUND=mklost_found
export MKMANIFEST=mkmanifest
export MK_MODMAP=mk_modmap
export MKNOD=mknod
export MKNTFS=mkntfs
export MKSQUASHFS=mksquashfs
export MKSWAP=mkswap
export MKTEMP=mktemp
export MLABEL=mlabel
export MMCLI=mmcli
export MMD=mmd
export MMOUNT=mmount
export MMOVE=mmove
export MODEMMANAGER=ModemManager
export MODINFO=modinfo
export MODPROBE=modprobe
export MOKUTIL=mokutil
export MONITOR_SENSOR=monitor_sensor
export MORE=more
export MOUNT=mount
export MOUNT_FUSE=mount_fuse
export MOUNT_FUSE3=mount_fuse3
export MOUNT_LOWNTFS_3G=mount_lowntfs_3g
export MOUNT_NTFS=mount_ntfs
export MOUNT_NTFS_3G=mount_ntfs_3g
export MOUNTPOINT=mountpoint
export MPARTITION=mpartition
export MPRIS_PROXY=mpris_proxy
export MRD=mrd
export MREN=mren
export MSHORTNAME=mshortname
export MSHOWFAT=mshowfat
export MT=mt
export MT_GNU=mt_gnu
export MTOOLS=mtools
export MTOOLSTEST=mtoolstest
export MTRACE=mtrace
export MTYPE=mtype
export MUNCHLIST=munchlist
export MV=mv
export MXTAR=mxtar
export MZIP=mzip
export NAMEI=namei
export NANO=nano
export NANOID=nanoid
export NASM=nasm
export NAUTILUS=nautilus
export NAUTILUS_AUTORUN_SOFTWARE=nautilus_autorun_software
export NAWK=nawk

export NDISASM=ndisasm
export NEQN=neqn
export NETCAT=netcat
export NETWORKCTL=networkctl
export NETWORKMANAGER=NetworkManager
export NEWGRP=newgrp
export NEWUSERS=newusers
export NFNL_OSF=nfnl_osf
export NFT=nft
export NGETTEXT=ngettext
export NICE=nice
export NISDOMAINNAME=nisdomainname
export NL=nl
export NM=nm
export NM_APPLET=nm_applet
export NMCLI=nmcli
export NM_CONNECTION_EDITOR=nm_connection_editor
export NM_ONLINE=nm_online
export NMTUI=nmtui
export NMTUI_CONNECT=nmtui_connect
export NMTUI_EDIT=nmtui_edit
export NMTUI_HOSTNAME=nmtui_hostname
export NODE=node
export NODE_COVERALLS=node_coveralls
export NODE_GYP=node_gyp
export NODEJS=nodejs
export NOHUP=nohup
export NOLOGIN=nologin
export NORMALIZER=normalizer
export NOTIFY_SEND=notify_send
export NOTION_APP_ENHANCED=notion_app_enhanced
export NPM=npm
export NPM_ARBORIST=npm_arborist
export NPROC=nproc
export NPX=npx
export NROFF=nroff
export NSENTER=nsenter
export NSLOOKUP=nslookup
export NSTAT=nstat
export NSUPDATE=nsupdate
export NTFS_3G=ntfs_3g
export NTFS_3G_PROBE=ntfs_3g_probe
export NTFSCAT=ntfscat
export NTFSCLONE=ntfsclone
export NTFSCLUSTER=ntfscluster
export NTFSCMP=ntfscmp
export NTFSCP=ntfscp
export NTFSDECRYPT=ntfsdecrypt
export NTFSFALLOCATE=ntfsfallocate
export NTFSFIX=ntfsfix
export NTFSINFO=ntfsinfo
export NTFSLABEL=ntfslabel
export NTFSLS=ntfsls
export NTFSMOVE=ntfsmove
export NTFSRECOVER=ntfsrecover
export NTFSRESIZE=ntfsresize
export NTFSSECAUDIT=ntfssecaudit
export NTFSTRUNCATE=ntfstruncate
export NTFSUNDELETE=ntfsundelete
export NTFSUSERMAP=ntfsusermap
export NTFSWIPE=ntfswipe
export NUMFMT=numfmt
export NV_CONTROL_DPY=nv_control_dpy
export NVIDIA_BUG_REPORT_SH=nvidia_bug_report_sh
export NVIDIA_DEBUGDUMP=nvidia_debugdump
export NVIDIA_DETECT=nvidia_detect
export NVIDIA_MODPROBE=nvidia_modprobe
export NVIDIA_PERSISTENCED=nvidia_persistenced
export NVIDIA_SETTINGS=nvidia_settings
export NVIDIA_SLEEP_SH=nvidia_sleep_sh
export NVIDIA_SMI=nvidia_smi
export NYC=nyc
export OBEXCTL=obexctl
export OBJCOPY=objcopy
export OBJDUMP=objdump
export OCLOCK=oclock
export OCSPTOOL=ocsptool
export OD=od
export OKTETA=okteta
export OPEN=open
export OPENER=opener
export OPENSSL=openssl
export OPENVT=openvt
export ORCA=orca
export ORCA_DM_WRAPPER=orca_dm_wrapper
export OSIRROX=osirrox
export OS_PROBER=os_prober
export OWNERSHIP=ownership
export P11_KIT=p11_kit
export P11TOOL=p11tool
export P7ZIP=p7zip
export PACOTE=pacote
export PAGER=pager
export PAM_AUTH_UPDATE=pam_auth_update
export PAM_GETENV=pam_getenv
export PAM_NAMESPACE_HELPER=pam_namespace_helper
export PAM_TIMESTAMP_CHECK=pam_timestamp_check
export PAPERCONF=paperconf
export PAPERCONFIG=paperconfig
export PARTED=parted
export PARTPROBE=partprobe
export PARTX=partx
export PASSWD=passwd
export PASTE=paste
export PATCH=patch
export PATHCHK=pathchk
export PDATA_TOOLS=pdata_tools
export PDB3=pdb3
export PDB3_11=pdb3_11
export PDF2DSC=pdf2dsc
export PDF2PS=pdf2ps
export PDFATTACH=pdfattach
export PDFDETACH=pdfdetach
export PDFFONTS=pdffonts
export PDFIMAGES=pdfimages
export PDFINFO=pdfinfo
export PDFSEPARATE=pdfseparate
export PDFSIG=pdfsig
export PDFTOCAIRO=pdftocairo
export PDFTOHTML=pdftohtml
export PDFTOPPM=pdftoppm
export PDFTOPS=pdftops
export PDFTOTEXT=pdftotext
export PDFUNITE=pdfunite
export PEEKFD=peekfd
export PERL=perl
export PERL5_36_0=perl5_36_0
export PERL5_36_X86_64_LINUX_GNU=perl5_36_x86_64_linux_gnu
export PERLBUG=perlbug
export PERLDOC=perldoc
export PERLI11NDOC=perli11ndoc
export PERLIVP=perlivp
export PERLTHANKS=perlthanks
export PF2AFM=pf2afm
export PFBTOPFA=pfbtopfa
export PGREP=pgrep
export PIC=pic
export PICO=pico
export PICONV=piconv
export PIDOF=pidof
export PIDWAIT=pidwait
export PINENTRY=pinentry
export PINENTRY_GNOME3=pinentry_gnome3
export PINENTRY_X11=pinentry_x11
export PING=ping
export PING4=ping4
export PING6=ping6
export PINKY=pinky
export PIPEWIRE=pipewire
export PIPEWIRE_AVB=pipewire_avb
export PIPEWIRE_PULSE=pipewire_pulse
export PIVOT_ROOT=pivot_root
export PKACTION=pkaction
export PKCHECK=pkcheck
export PKCON=pkcon
export PKEXEC=pkexec
export PKILL=pkill
export PKMON=pkmon
export PKTTYAGENT=pkttyagent
export PL2PM=pl2pm
export PLDD=pldd
export PLOG=plog
export PLYMOUTH=plymouth
export PLYMOUTHD=plymouthd
export PLYMOUTH_SET_DEFAULT_THEME=plymouth_set_default_theme
export PMAP=pmap
export POD2HTML=pod2html
export POD2MAN=pod2man
export POD2TEXT=pod2text
export POD2USAGE=pod2usage
export PODCHECKER=podchecker
export POFF=poff
export PON=pon
export POPD=popd
export PORTABLECTL=portablectl
export POST=POST
export POWEROFF=poweroff
export POWERPROFILESCTL=powerprofilesctl
export PPDC=ppdc
export PPDHTML=ppdhtml
export PPDI=ppdi
export PPDMERGE=ppdmerge
export PPDPO=ppdpo
export PPHS=pphs
export PPPD=pppd
export PPPDUMP=pppdump
export PPPOE_DISCOVERY=pppoe_discovery
export PPPSTATS=pppstats
export PR=pr
export PRECAT=precat
export PRECONV=preconv
export PREPARETIPS5=preparetips5
export PREUNZIP=preunzip
export PREZIP=prezip
export PREZIP_BIN=prezip_bin
export PRINT=print
export PRINTAFM=printafm
export PRINTENV=printenv
export PRINTF=printf
export PRLIMIT=prlimit
export PROTOCOLTOJSON=protocoltojson
export PROVE=prove
export PRTSTAT=prtstat
export PS=ps
export PS2ASCII=ps2ascii
export PS2EPSI=ps2epsi
export PS2PDF=ps2pdf
export PS2PDF12=ps2pdf12
export PS2PDF13=ps2pdf13
export PS2PDF14=ps2pdf14
export PS2PDFWR=ps2pdfwr
export PS2PS=ps2ps
export PS2PS2=ps2ps2
export PS2TXT=ps2txt
export PSFADDTABLE=psfaddtable
export PSFGETTABLE=psfgettable
export PSFSTRIPTABLE=psfstriptable
export PSFXTABLE=psfxtable
export PSKTOOL=psktool
export PSLOG=pslog
export PSTREE=pstree
export PSTREE_X11=pstree_x11
export PTAR=ptar
export PTARDIFF=ptardiff
export PTARGREP=ptargrep
export PTKED=ptked
export PTKSH=ptksh
export PTX=ptx
export PUSHD=pushd
export PVCHANGE=pvchange
export PVCK=pvck
export PVCREATE=pvcreate
export PVDISPLAY=pvdisplay
export PVMOVE=pvmove
export PVREMOVE=pvremove
export PVRESIZE=pvresize
export PVS=pvs
export PVSCAN=pvscan
export PW_CAT=pw_cat
export PWCK=pwck
export PW_CLI=pw_cli
export PWCONV=pwconv
export PWD=pwd
export PW_DOT=pw_dot
export PW_DSDPLAY=pw_dsdplay
export PW_DUMP=pw_dump
export PWDX=pwdx
export PWHISTORY_HELPER=pwhistory_helper
export PW_LINK=pw_link
export PW_LOOPBACK=pw_loopback
export PW_METADATA=pw_metadata
export PW_MIDIDUMP=pw_mididump
export PW_MIDIPLAY=pw_midiplay
export PW_MIDIRECORD=pw_midirecord
export PW_MON=pw_mon
export PW_PLAY=pw_play
export PW_PROFILER=pw_profiler
export PW_RECORD=pw_record
export PW_RESERVE=pw_reserve
export PW_TOP=pw_top
export PWUNCONV=pwunconv
export PY3CLEAN=py3clean
export PY3COMPILE=py3compile
export PY3VERSIONS=py3versions
export PYCHARM=pycharm
export PYDOC3=pydoc3
export PYDOC3_11=pydoc3_11
export PYGETTEXT3=pygettext3
export PYGETTEXT3_11=pygettext3_11
export PYTHON3=python3
export PYTHON3_11=python3_11
export PZSTD=pzstd
export QEMU_IMG=qemu_img
export QEMU_IO=qemu_io
export QEMU_NBD=qemu_nbd
export QEMU_PR_HELPER=qemu_pr_helper
export QEMU_STORAGE_DAEMON=qemu_storage_daemon
export QEMU_SYSTEM_AARCH64=qemu_system_aarch64
export QEMU_SYSTEM_ALPHA=qemu_system_alpha
export QEMU_SYSTEM_ARM=qemu_system_arm
export QEMU_SYSTEM_AVR=qemu_system_avr
export QEMU_SYSTEM_CRIS=qemu_system_cris
export QEMU_SYSTEM_HPPA=qemu_system_hppa
export QEMU_SYSTEM_I386=qemu_system_i386
export QEMU_SYSTEM_LOONGARCH64=qemu_system_loongarch64
export QEMU_SYSTEM_M68K=qemu_system_m68k
export QEMU_SYSTEM_MICROBLAZE=qemu_system_microblaze
export QEMU_SYSTEM_MICROBLAZEEL=qemu_system_microblazeel
export QEMU_SYSTEM_MIPS=qemu_system_mips
export QEMU_SYSTEM_MIPS64=qemu_system_mips64
export QEMU_SYSTEM_MIPS64EL=qemu_system_mips64el
export QEMU_SYSTEM_MIPSEL=qemu_system_mipsel
export QEMU_SYSTEM_NIOS2=qemu_system_nios2
export QEMU_SYSTEM_OR1K=qemu_system_or1k
export QEMU_SYSTEM_PPC=qemu_system_ppc
export QEMU_SYSTEM_PPC64=qemu_system_ppc64
export QEMU_SYSTEM_PPC64LE=qemu_system_ppc64le
export QEMU_SYSTEM_RISCV32=qemu_system_riscv32
export QEMU_SYSTEM_RISCV64=qemu_system_riscv64
export QEMU_SYSTEM_RX=qemu_system_rx
export QEMU_SYSTEM_S390X=qemu_system_s390x
export QEMU_SYSTEM_SH4=qemu_system_sh4
export QEMU_SYSTEM_SH4EB=qemu_system_sh4eb
export QEMU_SYSTEM_SPARC=qemu_system_sparc
export QEMU_SYSTEM_SPARC64=qemu_system_sparc64
export QEMU_SYSTEM_TRICORE=qemu_system_tricore
export QEMU_SYSTEM_X86_64=qemu_system_x86_64
export QEMU_SYSTEM_X86_64_MICROVM=qemu_system_x86_64_microvm
export QEMU_SYSTEM_XTENSA=qemu_system_xtensa
export QEMU_SYSTEM_XTENSAEB=qemu_system_xtensaeb
export QMICLI=qmicli
export QMI_FIRMWARE_UPDATE=qmi_firmware_update
export QMI_NETWORK=qmi_network
export QRCODE_TERMINAL=qrcode_terminal
export QUADRAPASSEL=quadrapassel
export QUERYBTS=querybts
export QUOTE=quote
export QUOTE_READLINE=quote_readline
export RANLIB=ranlib
export RBASH=rbash
export RCTEST=rctest
export RDMA=rdma
export READ=read
export READARRAY=readarray
export READELF=readelf
export READLINK=readlink
export READONLY=readonly
export READPROFILE=readprofile
export REALM=realm
export REALPATH=realpath
export REBOOT=reboot
export REGJSPARSER=regjsparser
export REMOTE_VIEWER=remote_viewer
export REMOVE_DEFAULT_ISPELL=remove_default_ispell
export REMOVE_DEFAULT_WORDLIST=remove_default_wordlist
export REMOVE_SHELL=remove_shell
export RENAME_UL=rename_ul
export RENDERCHECK=rendercheck
export RENICE=renice
export REPORTBUG=reportbug
export REPORT_HW=report_hw
export RESET=reset
export RESIZE2FS=resize2fs
export RESIZECONS=resizecons
export RESIZEPART=resizepart
export RETURN=return
export REV=rev
export RFCOMM=rfcomm
export RGREP=rgrep
export RHYTHMBOX=rhythmbox
export RHYTHMBOX_CLIENT=rhythmbox_client
export RIMRAF=rimraf
export RM=rm
export RMDIR=rmdir
export RMMOD=rmmod
export RMT=rmt
export RMT_TAR=rmt_tar
export RNANO=rnano
export ROTATELOGS=rotatelogs
export ROUTEL=routel
export RPCGEN=rpcgen
export RSTART=rstart
export RSTARTD=rstartd
export RTACCT=rtacct
export RTCWAKE=rtcwake
export RTKITCTL=rtkitctl
export RTMON=rtmon
export RTSTAT=rtstat
export RUNCON=runcon
export RUNLEVEL=runlevel
export RUN_MAILCAP=run_mailcap
export RUN_PARTS=run_parts
export RUNUSER=runuser
export RUN_WITH_ASPELL=run_with_aspell
export RVIEW=rview
export RYGEL=rygel
export SANED=saned
export SANE_FIND_SCANNER=sane_find_scanner
export SAVELOG=savelog
export SCALAR=scalar
export SCANIMAGE=scanimage
export SCP=scp
export SCP_DBUS_SERVICE=scp_dbus_service
export SCREENDUMP=screendump
export SCRIPT=script
export SCRIPTLIVE=scriptlive
export SCRIPTREPLAY=scriptreplay
export SDIFF=sdiff
export SDPTOOL=sdptool
export SEAHORSE=seahorse
export SED=sed
export SEE=see
export SELECT=select
export SELECT_DEFAULT_ISPELL=select_default_ispell
export SELECT_DEFAULT_IWRAP=select_default_iwrap
export SELECT_DEFAULT_WORDLIST=select_default_wordlist
export SELECT_EDITOR=select_editor
export SEMVER=semver
export SENSIBLE_BROWSER=sensible_browser
export SENSIBLE_EDITOR=sensible_editor
export SENSIBLE_PAGER=sensible_pager
export SEQ=seq
export SERVICE=service
export SESSREG=sessreg
export SET=set
export SETARCH=setarch
export SETCAP=setcap
export SETFACL=setfacl
export SETFONT=setfont
export SETKEYCODES=setkeycodes
export SETLEDS=setleds
export SETLOGCONS=setlogcons
export SETMETAMODE=setmetamode
export SETPCI=setpci
export SETPRIV=setpriv
export SETSID=setsid
export SETTERM=setterm
export SETUPCON=setupcon
export SETVESABLANK=setvesablank
export SETVTRGB=setvtrgb
export SETXKBMAP=setxkbmap
export SFDISK=sfdisk
export SFTP=sftp
export SG=sg
export SGDISK=sgdisk
export SH=sh
export SHA1SUM=sha1sum
export SHA224SUM=sha224sum
export SHA256SUM=sha256sum
export SHA384SUM=sha384sum
export SHA512SUM=sha512sum
export SHADOWCONFIG=shadowconfig
export SHASUM=shasum
export SHIFT=shift
export SHOPT=shopt
export SHOTWELL=shotwell
export SHOWCONSOLEFONT=showconsolefont
export SHOWFIGFONTS=showfigfonts
export SHOWKEY=showkey
export SHOWRGB=showrgb
export SHRED=shred
export SHUF=shuf
export SHUTDOWN=shutdown
export SIMPLE_SCAN=simple_scan
export SIZE=size
export SKILL=skill
export SLABTOP=slabtop
export SLEEP=sleep
export SLOGIN=slogin
export SMPROXY=smproxy
export SNAP=snap
export SNAPCTL=snapctl
export SNICE=snice
export SOELIM=soelim
export SOFFICE=soffice
export SOFTWARE_PROPERTIES_GTK=software_properties_gtk
export SOL=sol
export SORT=sort
export SOTRUSS=sotruss
export SOURCE=source
export SPA_ACP_TOOL=spa_acp_tool
export SPA_INSPECT=spa_inspect
export SPA_JSON_DUMP=spa_json_dump
export SPA_MONITOR=spa_monitor
export SPA_RESAMPLE=spa_resample
export SPD_CONF=spd_conf
export SPD_SAY=spd_say
export SPDSEND=spdsend
export SPEAKER_TEST=speaker_test
export SPEECH_DISPATCHER=speech_dispatcher
export SPLAIN=splain
export SPLIT=split
export SPLITFONT=splitfont
export SPLIT_LOGFILE=split_logfile
export SPROF=sprof
export SQFSCAT=sqfscat
export SQFSTAR=sqfstar
export SRPTOOL=srptool
export SS=ss
export SSH=ssh
export SSH_ADD=ssh_add
export SSH_AGENT=ssh_agent
export SSH_ARGV0=ssh_argv0
export SSH_COPY_ID=ssh_copy_id
export SSHD=sshd
export SSH_KEYGEN=ssh_keygen
export SSH_KEYSCAN=ssh_keyscan
export START_STOP_DAEMON=start_stop_daemon
export STARTX=startx
export STAT=stat
export STDBUF=stdbuf
export STREAMZIP=streamzip
export STRINGS=strings
export STRIP=strip
export STRUCT2OSD=struct2osd
export STTY=stty
export SU=su
export SUDO=sudo
export SUDOEDIT=sudoedit
export SUDO_LOGSRVD=sudo_logsrvd
export SUDOREPLAY=sudoreplay
export SUDO_SENDLOG=sudo_sendlog
export SULOGIN=sulogin
export SUM=sum
export SUSHI=sushi
export SUSPEND=suspend
export SWAPLABEL=swaplabel
export SWAPOFF=swapoff
export SWAPON=swapon
export SWELL_FOOP=swell_foop
export SWITCHEROOCTL=switcherooctl
export SWITCH_ROOT=switch_root
export SWTPM=swtpm
export SWTPM_BIOS=swtpm_bios
export SWTPM_CERT=swtpm_cert
export SWTPM_IOCTL=swtpm_ioctl
export SWTPM_LOCALCA=swtpm_localca
export SWTPM_SETUP=swtpm_setup
export SYNAPTIC=synaptic
export SYNAPTIC_PKEXEC=synaptic_pkexec
export SYNC=sync
export SYSCTL=sysctl
export SYSTEMCTL=systemctl
export SYSTEMD=systemd
export SYSTEMD_ANALYZE=systemd_analyze
export SYSTEMD_ASK_PASSWORD=systemd_ask_password
export SYSTEMD_CAT=systemd_cat
export SYSTEMD_CGLS=systemd_cgls
export SYSTEMD_CGTOP=systemd_cgtop
export SYSTEMD_CREDS=systemd_creds
export SYSTEMD_CRYPTENROLL=systemd_cryptenroll
export SYSTEMD_DELTA=systemd_delta
export SYSTEMD_DETECT_VIRT=systemd_detect_virt
export SYSTEMD_DISSECT=systemd_dissect
export SYSTEMD_ESCAPE=systemd_escape
export SYSTEMD_FIRSTBOOT=systemd_firstboot
export SYSTEMD_HWDB=systemd_hwdb
export SYSTEMD_ID128=systemd_id128
export SYSTEMD_INHIBIT=systemd_inhibit
export SYSTEMD_MACHINE_ID_SETUP=systemd_machine_id_setup
export SYSTEMD_MOUNT=systemd_mount
export SYSTEMD_NOTIFY=systemd_notify
export SYSTEMD_NSPAWN=systemd_nspawn
export SYSTEMD_PATH=systemd_path
export SYSTEMD_REPART=systemd_repart
export SYSTEMD_RUN=systemd_run
export SYSTEMD_SOCKET_ACTIVATE=systemd_socket_activate
export SYSTEMD_STDIO_BRIDGE=systemd_stdio_bridge
export SYSTEMD_SYSEXT=systemd_sysext
export SYSTEMD_SYSUSERS=systemd_sysusers
export SYSTEMD_TMPFILES=systemd_tmpfiles
export SYSTEMD_TTY_ASK_PASSWORD_AGENT=systemd_tty_ask_password_agent
export SYSTEMD_UMOUNT=systemd_umount
export SYSTEMSETTINGS=systemsettings
export SYSTEMSETTINGS5=systemsettings5
export TABS=tabs
export TAC=tac
export TAIL=tail
export TALI=tali
export TAP=tap
export TAPE=tape
export TAP_MOCHA_REPORTER=tap_mocha_reporter
export TAP_PARSER=tap_parser
export TAR=tar
export TARCAT=tarcat
export TASKSEL=tasksel
export TASKSET=taskset
export TBL=tbl
export TC=tc
export TCPTRACEROUTE=tcptraceroute
export TCPTRACEROUTE_DB=tcptraceroute_db
export TEE=tee
export TELINIT=telinit
export TELNET=telnet
export TEMPFILE=tempfile
export TERSER=terser
export TEST=test
export TGZ=tgz
export THEN=then
export THIN_CHECK=thin_check
export THIN_DELTA=thin_delta
export THIN_DUMP=thin_dump
export THIN_LS=thin_ls
export THIN_METADATA_SIZE=thin_metadata_size
export THIN_REPAIR=thin_repair
export THIN_RESTORE=thin_restore
export THIN_RMAP=thin_rmap
export THIN_TRIM=thin_trim
export TIC=tic
export TIME=time
export TIMEDATECTL=timedatectl
export TIMEOUT=timeout
export TIMES=times
export TIPC=tipc
export TKJPEG=tkjpeg
export TLOAD=tload
export TOC2CDDB=toc2cddb
export TOC2CUE=toc2cue
export TOE=toe
export TOP=top
export TOTEM=totem
export TOTEM_VIDEO_THUMBNAILER=totem_video_thumbnailer
export TOUCH=touch
export TPUT=tput
export TR=tr
export TRACEPROTO=traceproto
export TRACEPROTO_DB=traceproto_db
export TRACEROUTE=traceroute
export TRACEROUTE6=traceroute6
export TRACEROUTE6_DB=traceroute6_db
export TRACEROUTE_DB=traceroute_db
export TRACEROUTE_NANOG=traceroute_nanog
export TRACKER3=tracker3
export TRANSMISSION_GTK=transmission_gtk
export TRANSSET=transset
export TRAP=trap
export TROFF=troff
export TRUE=true
export TRUNCATE=truncate
export TRUST=trust
export TRYAFFIX=tryaffix
export TSET=tset
export TSORT=tsort
export TTY=tty
export TUNE2FS=tune2fs
export TUNE_EXFAT=tune_exfat
export TYPE=type
export TYPESET=typeset
export TZSELECT=tzselect
export UBUNTU_CORE_LAUNCHER=ubuntu_core_launcher
export UCF=ucf
export UCFQ=ucfq
export UCFR=ucfr
export UCLAMPSET=uclampset
export UCS2ANY=ucs2any
export UDEVADM=udevadm
export UDISKSCTL=udisksctl
export UL=ul
export ULIMIT=ulimit
export UMASK=umask
export UMAX_PP=umax_pp
export UMOUNT=umount
export UMOUNT_UDISKS2=umount_udisks2
export UNALIAS=unalias
export UNAME=uname
export UNCOMPRESS=uncompress
export UNEXPAND=unexpand
export UNICODE_START=unicode_start
export UNICODE_STOP=unicode_stop
export UNIQ=uniq
export UNITY_SCOPE_LOADER=unity_scope_loader
export UNIX_CHKPWD=unix_chkpwd
export UNIX_UPDATE=unix_update
export UNLINK=unlink
export UNLZMA=unlzma
export UNMKINITRAMFS=unmkinitramfs
export UNOPKG=unopkg
export UNSET=unset
export UNSHARE=unshare
export UNSQUASHFS=unsquashfs
export UNTIL=until
export UNXZ=unxz
export UNZIP=unzip
export UNZIPSFX=unzipsfx
export UNZSTD=unzstd
export UPDATE_ALTERNATIVES=update_alternatives
export UPDATE_CA_CERTIFICATES=update_ca_certificates
export UPDATE_CATALOG=update_catalog
export UPDATE_CRACKLIB=update_cracklib
export UPDATE_DEFAULT_ASPELL=update_default_aspell
export UPDATE_DEFAULT_ISPELL=update_default_ispell
export UPDATE_DEFAULT_WORDLIST=update_default_wordlist
export UPDATE_DESKTOP_DATABASE=update_desktop_database
export UPDATE_DICTCOMMON_ASPELL=update_dictcommon_aspell
export UPDATE_DICTCOMMON_HUNSPELL=update_dictcommon_hunspell
export UPDATE_FONTS_ALIAS=update_fonts_alias
export UPDATE_FONTS_DIR=update_fonts_dir
export UPDATE_FONTS_SCALE=update_fonts_scale
export UPDATE_GLX=update_glx
export UPDATE_GRUB=update_grub
export UPDATE_GRUB2=update_grub2
export UPDATE_GSFONTMAP=update_gsfontmap
export UPDATE_ICON_CACHES=update_icon_caches
export UPDATE_INETD=update_inetd
export UPDATE_INITRAMFS=update_initramfs
export UPDATE_LOCALE=update_locale
export UPDATE_MIME=update_mime
export UPDATE_MIME_DATABASE=update_mime_database
export UPDATE_PASSWD=update_passwd
export UPDATE_PCIIDS=update_pciids
export UPDATE_RC_D=update_rc_d
export UPDATE_SECUREBOOT_POLICY=update_secureboot_policy
export UPDATE_SHELLS=update_shells
export UPDATE_XMLCATALOG=update_xmlcatalog
export UPOWER=upower
export UPTIME=uptime
export USB_DEVICES=usb_devices
export USBHID_DUMP=usbhid_dump
export USB_MODESWITCH=usb_modeswitch
export USB_MODESWITCH_DISPATCHER=usb_modeswitch_dispatcher
export USBMUXD=usbmuxd
export USBRESET=usbreset
export USERADD=useradd
export USERDEL=userdel
export USERMOD=usermod
export USERS=users
export UTMPDUMP=utmpdump
export UZ=uz
export VALIDLOCALE=validlocale
export VCSTIME=vcstime
export VDIR=vdir
export VDPA=vdpa
export VGCFGBACKUP=vgcfgbackup
export VGCFGRESTORE=vgcfgrestore
export VGCHANGE=vgchange
export VGCK=vgck
export VGCONVERT=vgconvert
export VGCREATE=vgcreate
export VGDISPLAY=vgdisplay
export VGEXPORT=vgexport
export VGEXTEND=vgextend
export VGIMPORT=vgimport
export VGIMPORTCLONE=vgimportclone
export VGMERGE=vgmerge
export VGMKNODES=vgmknodes
export VGREDUCE=vgreduce
export VGREMOVE=vgremove
export VGRENAME=vgrename
export VGS=vgs
export VGSCAN=vgscan
export VGSPLIT=vgsplit
export VI=vi
export VIEW=view
export VIEWRES=viewres
export VIGR=vigr
export VIM_TINY=vim_tiny
export VIPW=vipw
export VIRSH=virsh
export VIRT_ADMIN=virt_admin
export VIRT_CLONE=virt_clone
export VIRT_HOST_VALIDATE=virt_host_validate
export VIRT_INSTALL=virt_install
export VIRTLOCKD=virtlockd
export VIRTLOGD=virtlogd
export VIRT_MANAGER=virt_manager
export VIRT_PKI_QUERY_DN=virt_pki_query_dn
export VIRT_PKI_VALIDATE=virt_pki_validate
export VIRT_QEMU_RUN=virt_qemu_run
export VIRT_SSH_HELPER=virt_ssh_helper
export VIRT_VIEWER=virt_viewer
export VIRT_XML=virt_xml
export VIRT_XML_VALIDATE=virt_xml_validate
export VISUDO=visudo
export VMSTAT=vmstat
export VMWARECTRL=vmwarectrl
export VPDDECODE=vpddecode
export W=w
export WAIT=wait
export WALL=wall
export WATCH=watch
export WATCHGNUPG=watchgnupg
export WC=wc
export WDCTL=wdctl
export WEBPACK=webpack
export WGET=wget
export WHATIS=whatis
export WHEREIS=whereis
export WHICH=which
export WHICH_DEBIANUTILS=which_debianutils
export WHILE=while
export WHIPTAIL=whiptail
export WHO=who
export WHOAMI=whoami
export WIDGET=widget
export WIPEFS=wipefs
export WIREPLUMBER=wireplumber
export WORD_LIST_COMPRESS=word_list_compress
export WPA_ACTION=wpa_action
export WPA_CLI=wpa_cli
export WPA_PASSPHRASE=wpa_passphrase
export WPA_SUPPLICANT=wpa_supplicant
export WPCTL=wpctl
export WPEXEC=wpexec
export WRITE=write
export WSCAT=wscat
export WWW_BROWSER=www_browser
export X=X
export X11=X11
export X11PERF=x11perf
export X11PERFCOMP=x11perfcomp
export X86_64=x86_64
export X86_64_LINUX_GNU_ADDR2LINE=x86_64_linux_gnu_addr2line
export X86_64_LINUX_GNU_AR=x86_64_linux_gnu_ar
export X86_64_LINUX_GNU_AS=x86_64_linux_gnu_as
export X86_64_LINUX_GNU_C_FILT=x86_64_linux_gnu_c_filt
export X86_64_LINUX_GNU_CPP=x86_64_linux_gnu_cpp
export X86_64_LINUX_GNU_CPP_12=x86_64_linux_gnu_cpp_12
export X86_64_LINUX_GNU_DWP=x86_64_linux_gnu_dwp
export X86_64_LINUX_GNU_ELFEDIT=x86_64_linux_gnu_elfedit
export X86_64_LINUX_GNU_G_=x86_64_linux_gnu_g_
export X86_64_LINUX_GNU_G__12=x86_64_linux_gnu_g__12
export X86_64_LINUX_GNU_GCC=x86_64_linux_gnu_gcc
export X86_64_LINUX_GNU_GCC_12=x86_64_linux_gnu_gcc_12
export X86_64_LINUX_GNU_GCC_AR=x86_64_linux_gnu_gcc_ar
export X86_64_LINUX_GNU_GCC_AR_12=x86_64_linux_gnu_gcc_ar_12
export X86_64_LINUX_GNU_GCC_NM=x86_64_linux_gnu_gcc_nm
export X86_64_LINUX_GNU_GCC_NM_12=x86_64_linux_gnu_gcc_nm_12
export X86_64_LINUX_GNU_GCC_RANLIB=x86_64_linux_gnu_gcc_ranlib
export X86_64_LINUX_GNU_GCC_RANLIB_12=x86_64_linux_gnu_gcc_ranlib_12
export X86_64_LINUX_GNU_GCOV=x86_64_linux_gnu_gcov
export X86_64_LINUX_GNU_GCOV_12=x86_64_linux_gnu_gcov_12
export X86_64_LINUX_GNU_GCOV_DUMP=x86_64_linux_gnu_gcov_dump
export X86_64_LINUX_GNU_GCOV_DUMP_12=x86_64_linux_gnu_gcov_dump_12
export X86_64_LINUX_GNU_GCOV_TOOL=x86_64_linux_gnu_gcov_tool
export X86_64_LINUX_GNU_GCOV_TOOL_12=x86_64_linux_gnu_gcov_tool_12
export X86_64_LINUX_GNU_GOLD=x86_64_linux_gnu_gold
export X86_64_LINUX_GNU_GP_ARCHIVE=x86_64_linux_gnu_gp_archive
export X86_64_LINUX_GNU_GP_COLLECT_APP=x86_64_linux_gnu_gp_collect_app
export X86_64_LINUX_GNU_GP_DISPLAY_HTML=x86_64_linux_gnu_gp_display_html
export X86_64_LINUX_GNU_GP_DISPLAY_SRC=x86_64_linux_gnu_gp_display_src
export X86_64_LINUX_GNU_GP_DISPLAY_TEXT=x86_64_linux_gnu_gp_display_text
export X86_64_LINUX_GNU_GPROF=x86_64_linux_gnu_gprof
export X86_64_LINUX_GNU_GPROFNG=x86_64_linux_gnu_gprofng
export X86_64_LINUX_GNU_LD=x86_64_linux_gnu_ld
export X86_64_LINUX_GNU_LD_BFD=x86_64_linux_gnu_ld_bfd
export X86_64_LINUX_GNU_LD_GOLD=x86_64_linux_gnu_ld_gold
export X86_64_LINUX_GNU_LTO_DUMP=x86_64_linux_gnu_lto_dump
export X86_64_LINUX_GNU_LTO_DUMP_12=x86_64_linux_gnu_lto_dump_12
export X86_64_LINUX_GNU_NM=x86_64_linux_gnu_nm
export X86_64_LINUX_GNU_OBJCOPY=x86_64_linux_gnu_objcopy
export X86_64_LINUX_GNU_OBJDUMP=x86_64_linux_gnu_objdump
export X86_64_LINUX_GNU_RANLIB=x86_64_linux_gnu_ranlib
export X86_64_LINUX_GNU_READELF=x86_64_linux_gnu_readelf
export X86_64_LINUX_GNU_SIZE=x86_64_linux_gnu_size
export X86_64_LINUX_GNU_STRINGS=x86_64_linux_gnu_strings
export X86_64_LINUX_GNU_STRIP=x86_64_linux_gnu_strip
export XARGS=xargs
export XAUTH=xauth
export XBIFF=xbiff
export XBRLAPI=xbrlapi
export XCALC=xcalc
export XCLIPBOARD=xclipboard
export XCLOCK=xclock
export XCMSDB=xcmsdb
export XCONSOLE=xconsole
export XCURSORGEN=xcursorgen
export XCUTSEL=xcutsel
export XDG_DBUS_PROXY=xdg_dbus_proxy
export XDG_DESKTOP_ICON=xdg_desktop_icon
export XDG_DESKTOP_MENU=xdg_desktop_menu
export XDG_EMAIL=xdg_email
export XDG_ICON_RESOURCE=xdg_icon_resource
export XDG_MIME=xdg_mime
export XDG_OPEN=xdg_open
export XDG_SCREENSAVER=xdg_screensaver
export XDG_SETTINGS=xdg_settings
export XDG_USER_DIR=xdg_user_dir
export XDG_USER_DIRS_GTK_UPDATE=xdg_user_dirs_gtk_update
export XDG_USER_DIRS_UPDATE=xdg_user_dirs_update
export XDITVIEW=xditview
export XDPYINFO=xdpyinfo
export XDRIINFO=xdriinfo
export XEDIT=xedit
export XEPHYR=Xephyr
export XEV=xev
export XEYES=xeyes
export XFD=xfd
export XFONTSEL=xfontsel
export XGAMMA=xgamma
export XGC=xgc
export XHOST=xhost
export XINIT=xinit
export XKBBELL=xkbbell
export XKBCOMP=xkbcomp
export XKBEVD=xkbevd
export XKBPRINT=xkbprint
export XKBSET=xkbset
export XKBSET_GUI=xkbset_gui
export XKBVLEDS=xkbvleds
export XKBWATCH=xkbwatch
export XKEYSTONE=xkeystone
export XKILL=xkill
export XLOAD=xload
export XLOGO=xlogo
export XLSATOMS=xlsatoms
export XLSCLIENTS=xlsclients
export XLSFONTS=xlsfonts
export XMAG=xmag
export XMAN=xman
export XMESSAGE=xmessage
export XMLCATALOG=xmlcatalog
export XMLLINT=xmllint
export XMODMAP=xmodmap
export XMORE=xmore
export XORG=Xorg
export XORRECORD=xorrecord
export XORRISO=xorriso
export XORRISOFS=xorrisofs
export XPROP=xprop
export XRANDR=xrandr
export XRDB=xrdb
export XREFRESH=xrefresh
export X_SESSION_MANAGER=x_session_manager
export XSET=xset
export XSETMODE=xsetmode
export XSETPOINTER=xsetpointer
export XSETROOT=xsetroot
export XSETWACOM=xsetwacom
export XSM=xsm
export XSTDCMAP=xstdcmap
export XSUBPP=xsubpp
export XTABLES_LEGACY_MULTI=xtables_legacy_multi
export XTABLES_MONITOR=xtables_monitor
export XTABLES_NFT_MULTI=xtables_nft_multi
export X_TERMINAL_EMULATOR=x_terminal_emulator
export XVIDTUNE=xvidtune
export XVINFO=xvinfo
export XWAYLAND=Xwayland
export XWD=xwd
export XWININFO=xwininfo
export XWUD=xwud
export X_WWW_BROWSER=x_www_browser
export XZ=xz
export XZCAT=xzcat
export XZCMP=xzcmp
export XZDIFF=xzdiff
export XZEGREP=xzegrep
export XZFGREP=xzfgrep
export XZGREP=xzgrep
export XZLESS=xzless
export XZMORE=xzmore
export YELP=yelp
export YES=yes
export YPDOMAINNAME=ypdomainname
export ZCAT=zcat
export ZCMP=zcmp
export ZDIFF=zdiff
export ZDUMP=zdump
export ZEGREP=zegrep
export ZENITY=zenity
export ZFGREP=zfgrep
export ZFORCE=zforce
export ZGREP=zgrep
export ZIC=zic
export ZIPDETAILS=zipdetails
export ZIPGREP=zipgrep
export ZIPINFO=zipinfo
export ZLESS=zless
export ZMORE=zmore
export ZNEW=znew
export ZRAMCTL=zramctl
export ZSTD=zstd
export ZSTDCAT=zstdcat
export ZSTDGREP=zstdgrep
export ZSTDLESS=zstdless
export ZSTDMT=zstdmt